// Web/cgt_react/src/main/Main.js
import mainstyle from "./Main.module.css";

function Main() {
  return (
    <div className={mainstyle.mainContainer}>
      <article>
        <section className={mainstyle.mainDescription}>
          <p>
            Caregiver tracker is used to manage care given to those who need it.
            Be it an infant or child or spouse or parent or friend, there arises
            a situation where they need to be taken care of in a regular manner.
            This caregiver tracker takes care of such needs.
          </p>
        </section>
        <section className={mainstyle.feedingTracker}>
          <p>
            Feeding tracker can be used to track different types of feeds. We
            can choose feeding types such as Breast feeding, Breast pumping,
            Formula feeding, Mashed food, Normal food, Water, Juices, etc.
            Feeding modes include Manual or Electric pump for Breast pumping,
            Feeding bottle, Spoon, Glass, etc. Feeding side would be visible for
            breast pumping and breast feeding. Tracking can be started and
            stopped. Upon finishing a tracking, feed quantity can be recorded.
            Feeds are listed under the Feeding tracker tab. Feeds can be edited
            and deleted. Feeds are listed datewise. Pumped feeds when fed are
            indented to show that.
          </p>
        </section>
        <section className={mainstyle.excretionTracker}>
          <p>
            Excretion tracker can be used to track urine, stools and both. Users
            are given the option to choose Diaper or other methods like cloth.
            Diaper field is populated when diapers are added to the inventory
            under inventory tracker. If Diaper is not listed under Inventory
            tracker, then it will not allow to add Excretion.
          </p>
        </section>
        <section className={mainstyle.medicationTracker}>
          <p>
            Medication tracker can be used to track medicines provided. Users
            are given the option to choose medicine in the form of drops, syrup,
            pills or tablets. Medicine field is populated when medicines are
            added to the inventory under inventory tracker. If medicine is not
            listed under Inventory tracker, then it will not allow to add
            Medication.
          </p>
        </section>
        <section className={mainstyle.inventoryTracker}>
          <p>Inventory</p>
        </section>
      </article>
    </div>
  );
}

export default Main;

// Web/cgt_angular/src/app/main/main.component.ts
import { Component } from '@angular/core';
import {
  animate,
  animation,
  style,
  transition,
  trigger,
  useAnimation,
} from '@angular/animations';

const slideFromRight = animation([
  style({ opacity: 0, transform: 'translateX(100%)' }),
  animate('1s', style({ opacity: 1, transform: 'translateX(0%)' })),
]);
const slideIntoRight = animation(
  animate('1s', style({ opacity: 0, transform: 'translateX(100%)' }))
);

const slideFromLeft = animation([
  style({ opacity: 0, transform: 'translateX(-100%)' }),
  animate('1s', style({ opacity: 1, transform: 'translateX(0%)' })),
]);
const slideIntoLeft = animation(
  animate('1s', style({ opacity: 0, transform: 'translateX(-100%)' }))
);

@Component({
  selector: 'app-main',
  templateUrl: './main.component.html',
  styleUrls: ['./main.component.css'],
  standalone: false,
  animations: [
    trigger('rightBlocks', [
      transition('void => *', useAnimation(slideFromRight)),
      transition('* => void', useAnimation(slideIntoRight)),
    ]),
    trigger('leftBlocks', [
      transition('void => *', useAnimation(slideFromLeft)),
      transition('* => void', useAnimation(slideIntoLeft)),
    ]),
  ],
})
export class MainComponent {
  envName: string;
}

<app-menubar></app-menubar>
<div class="main-container">
  <!-- <div
    class="sign-up-container container text-left bg-light bg-gradient shadow"
  >
    <app-signup></app-signup>
  </div>
  <div class="login-container container text-left bg-light bg-gradient shadow">
    <app-login></app-login>
  </div> -->
  <article>
    <section class="main-description" [@rightBlocks]>
      <p>
        Caregiver tracker is used to manage care given to those who need it. Be
        it an infant or child or spouse or parent or friend, there arises a
        situation where they need to be taken care of in a regular manner. This
        caregiver tracker takes care of such needs.
      </p>
    </section>
    <section class="feeding-tracker" [@leftBlocks]>
      <p>
        Feeding tracker can be used to track different types of feeds. We can
        choose feeding types such as Breast feeding, Breast pumping, Formula
        feeding, Mashed food, Normal food, Water, Juices, etc. Feeding modes
        include Manual or Electric pump for Breast pumping, Feeding bottle,
        Spoon, Glass, etc. Feeding side would be visible for breast pumping and
        breast feeding. Tracking can be started and stopped. Upon finishing a
        tracking, feed quantity can be recorded. Feeds are listed under the
        Feeding tracker tab. Feeds can be edited and deleted. Feeds are listed
        datewise. Pumped feeds when fed are indented to show that.
      </p>
    </section>
    <section class="excretion-tracker" [@rightBlocks]>
      <p>
        Excretion tracker can be used to track urine, stools and both. Users are
        given the option to choose Diaper or other methods like cloth. Diaper
        field is populated when diapers are added to the inventory under
        inventory tracker. If Diaper is not listed under Inventory tracker, then
        it will not allow to add Excretion.
      </p>
    </section>
    <section class="medication-tracker" [@leftBlocks]>
      <p>
        Medication tracker can be used to track medicines provided. Users are
        given the option to choose medicine in the form of drops, syrup, pills
        or tablets. Medicine field is populated when medicines are added to the
        inventory under inventory tracker. If medicine is not listed under
        Inventory tracker, then it will not allow to add Medication.
      </p>
    </section>
    <section class="inventory-tracker" [@rightBlocks]>
      <p>Inventory</p>
    </section>
  </article>
</div>
